# Generated by Django 5.2.3 on 2025-06-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='An image for the post (optional)', null=True, upload_to='posts/'),
        ),
    ]
